name: 'Build Changelog from PR'
description: 'Build Changelog from recent PR title and body'
env:
  pr:
    description: 'PR object, passed as ENV, not with INPUT'
    required: true
inputs:
  version:
    description: 'The current version to be displayed'
    required: true
  message-pattern:
    description: 'anything to match from the commit and PR messages'
    default: 'https://[\wéáőúíóüö/\-\.]+'
    required: false
  body-template:
    description: 'The changelog content syntax'
    default: '## {{version}} - {{date}}\n\n{ - {message}\n}'
    required: false
outputs:
  new:
    description: 'The newly created changelog content'
  diff:
    description: 'The changelog difference compare to the last tag, currently not implemented'
runs:
  using: 'node12'
  main: 'index.js'
